# Generated by Django 3.2.7 on 2022-01-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_dater',
            new_name='created_date',
        ),
    ]
